development:
  adapter: postgresql
  database: appa_dev
  pool: 5
  timeout: 5000

test:
  adapter: postgresql
  database: appa_test
  pool: 5
  timeout: 5000

production:
  adapter: postgresql
  database: appa_prod
  pool: 5
  timeout: 5000
